apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  index.html: |
    {{ .Files.Get "static/index.html" | nindent 4 }}
  styles.css: |
    {{ .Files.Get "static/styles.css" | nindent 4 }}
  script.js: |
    const DASHBOARD_PORT = {{ add .Values.service.nodePort 1 }};
    const GLANCES_PORT = {{ sub .Values.service.nodePort 1 }};
    {{ .Files.Get "static/script.js" | nindent 4 }} 