apiVersion: v1
kind: Service
metadata:
  name: glances
  labels:
    app: glances
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 61208
    nodePort: {{ .Values.service.nodePort }}
    protocol: TCP
    name: http
  selector:
    app: glances 